---
- name: Ensure config file directory exists
  file: "path={{ docker_config_file | dirname }} state=directory"
  when: docker_opts is defined and docker_opts is not none

- name: Configure docker options
  template: "src={{ docker_config_template }} dest={{ docker_config_file }}"
  notify: restart docker
  when: docker_opts is defined and docker_opts is not none

- name: Configure docker environments
  include: "configure-{{ ansible_service_mgr }}.yml"
  static: no

- name: Add users to docker group
  user: "name={{ item }} append=yes groups=docker"
  with_items: "{{ docker_users }}"
  when: docker_users is defined and docker_users is not none
