---
# Include variables and define needed variables.
- name: Include OS-specific variables
  include_vars: "{{ ansible_distribution }}.yml"

# Setup/install tasks.
- include: "setup-{{ ansible_distribution }}.yml"
  static: no

# Configure Docker.
- include: "configure-{{ ansible_distribution }}.yml"
  static: no

- name: Ensure Docker has selected state and enabled on boot.
  service:
    name: "{{ docker_service }}"
    state: "{{ docker_state }}"
    enabled: yes
